package com.fordoctors.fordoctors

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.support.design.widget.FloatingActionButton
import android.support.v7.app.AlertDialog
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.LinearLayoutManager
import android.support.v7.widget.RecyclerView
import android.view.LayoutInflater
import android.widget.ArrayAdapter
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.Toast
import com.bumptech.glide.Glide
import com.fordoctors.fordoctors.adapter.MedicineAdapter
import com.fordoctors.fordoctors.helper.EncryptionHelper
import com.fordoctors.fordoctors.helper.QRCodeHelper
import com.fordoctors.fordoctors.model.Medicine
import com.fordoctors.fordoctors.model.PrescriptionObjects
import com.fordoctors.fordoctors.model.ProfileObjects
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.*
import com.google.gson.Gson
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel
import kotlinx.android.synthetic.main.activity_add_prescription.*
import kotlinx.android.synthetic.main.activity_qrcode.*
import kotlinx.android.synthetic.main.single_medicine_dialog.view.*
import java.text.SimpleDateFormat
import java.util.*
import kotlin.collections.ArrayList

class AddPrescriptionActivity : AppCompatActivity() {

    companion object {
        private const val SCANNED_STRING: String = "scanned_string"
        fun getScannedActivity(callingClassContext: Context, encryptedString: String): Intent {
            return Intent(callingClassContext, AddPrescriptionActivity::class.java)
                    .putExtra(SCANNED_STRING, encryptedString)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_add_prescription)
        if (intent.getSerializableExtra(SCANNED_STRING) == null)
            throw RuntimeException("No encrypted String found in intent")
        val decryptedString = EncryptionHelper.getInstance().getDecryptionString(intent.getStringExtra(SCANNED_STRING))
        val userObject = Gson().fromJson(decryptedString, ProfileObjects::class.java)

        Glide.with(this).load(userObject.Profile_Image).into(profile_image);
        add_prescription_name.text = userObject.Name
        add_prescription_email.text = userObject.Email
        add_prescription_age.text = userObject.Age
        add_prescription_gender.text = userObject.Gender
        add_prescription_city.text = userObject.City
        add_prescription_state.text = userObject.State
        add_prescription_country.text = userObject.Country

        var mAuth : FirebaseAuth = FirebaseAuth.getInstance()
        var mCurrentUserId = mAuth.getCurrentUser()?.getUid()

        var mPatientDatabase: DatabaseReference = FirebaseDatabase.getInstance().reference.child("Patients").child(mCurrentUserId)
        mPatientDatabase.keepSynced(true)
        var mUserDatabase: DatabaseReference = FirebaseDatabase.getInstance().reference.child("Users").child(mCurrentUserId)
        mUserDatabase.keepSynced(true)
        val key: String = mPatientDatabase.push().getKey()

        val recyclerView = findViewById(R.id.prescription_list) as RecyclerView
        recyclerView.layoutManager = LinearLayoutManager(this, LinearLayout.VERTICAL, false)
        val users = ArrayList<Medicine>()
        val edit_text_details = findViewById(R.id.add_prescription_details) as EditText
        val btn_click_me = findViewById(R.id.add_prescription) as FloatingActionButton
        btn_click_me.setOnClickListener {
            val mDialogView = LayoutInflater.from(this).inflate(R.layout.single_medicine_dialog, null)
            val mBuilder = AlertDialog.Builder(this)
                    .setView(mDialogView)
                    .setTitle("Add Medicine")
            val  mAlertDialog = mBuilder.show()
            val med:Array<String> = arrayOf("Abacavir Sulfate",
                    "Abatacept",
                    "Abilify",
                    "Acamprosate Calcium",
                    "Accretropin",
                    "Aceon",
                    "Aci-Jel",
                    "Acthrel",
                    "Actimmune",
                    "Actisite",
                    "Acular",
                    "Acular LS",
                    "Acuvail",
                    "Adagen",
                    "Adapalene",
                    "Adcirca",
                    "Adefovir Dipivoxil",
                    "Adenoscan",
                    "Adenosine",
                    "Adipex-P",
                    "AdreView",
                    "Advair HFA",
                    "Aerospan HFA",
                    "Agalsidase Beta",
                    "Aggrenox",
                    "Akineton",
                    "Alamast",
                    "Albenza",
                    "Aldactazide",
                    "Aldactone",
                    "Aldoril",
                    "Aldurazyme",
                    "Alemtuzumab",
                    "Alglucosidase Alfa",
                    "Allegra-D",
                    "Allegra D 24 Hour",
                    "Alli",
                    "Aloprim",
                    "Alora",
                    "Alphanate",
                    "Altace",
                    "Altocor",
                    "Altoprev",
                    "Alupent",
                    "Amantadine Hydrochloride",
                    "Amerge",
                    "Amifostine",
                    "Amiloride",
                    "Aminosalicylic Acid",
                    "Aminosyn II 8.5%",
                    "Amlodipine Besylate",
                    "Amoxapine",
                    "Amytal Sodium",
                    "Anabolic steroids",
                    "Anadrol-50",
                    "Antithrombin",
                    "Antivenin",
                    "Antivert",
                    "Aredia",
                    "Aricept",
                    "Armodafinil",
                    "Arranon",
                    "Artane",
                    "Asclera",
                    "Ascorbic Acid",
                    "Astemizole",
                    "Atacand",
                    "Atacand HCT",
                    "Atazanavir Sulfate",
                    "Atomoxetine HCl",
                    "Atridox",
                    "Atripla",
                    "Atropen",
                    "Augmentin XR",
                    "Avage",
                    "Avandia",
                    "Avastin",
                    "Avinza",
                    "Axid",
                    "Azasan",
                    "Azasite",
                    "Azelaic Acid",
                    "Azelastine Hydrochloride",
                    "Azilect",
                    "Azmacort",
                    "Balsalazide",
                    "Benazepril",
                    "Benzocaine",
                    "Benzoyl Peroxide Gel",
                    "Benzphetamine",
                    "Benztropine Mesylate",
                    "Bepreve",
                    "Betagan",
                    "Bethanechol",
                    "Betimol",
                    "Betoptic S",
                    "Bevacizumab",
                    "BiCNU",
                    "Biperiden",
                    "Bismuth Subcitrate Potassium",
                    "Bismuth Subsalicylate",
                    "Blocadren",
                    "Boniva",
                    "Bontril",
                    "Boostrix",
                    "Botulinum Toxin Type A",
                    "Bravelle",
                    "Brevibloc",
                    "Bromocriptine Mesylate",
                    "Brovana",
                    "Budesonide",
                    "Buprenorphine",
                    "Buspar",
                    "Buspirone",
                    "Busulfan",
                    "Busulfex",
                    "Cabergoline",
                    "Caduet",
                    "Calcitonin-Salmon",
                    "Calcium Chloride",
                    "Calcium Disodium Versenate",
                    "Calcium Gluconate",
                    "Campral",
                    "Canasa",
                    "Cancidas",
                    "Captopril",
                    "Carac",
                    "Carbatrol",
                    "Cardiolite",
                    "Carisoprodol",
                    "Carmustine",
                    "Carvedilol",
                    "Casodex",
                    "Caspofungin Acetate",
                    "Cataflam",
                    "Catapres",
                    "Catapres-TTS",
                    "Caverject",
                    "Cedax",
                    "Cefditoren Pivoxil",
                    "Cefixime",
                    "Cefizox",
                    "Cefotetan",
                    "Ceftazidime",
                    "Ceftibuten",
                    "Ceftin",
                    "Cefzil",
                    "Celestone Soluspan",
                    "Celexa",
                    "CellCept",
                    "Cellulose",
                    "Celontin",
                    "Cephalexin",
                    "Cerebyx",
                    "Ceretec",
                    "Cerubidine",
                    "Cerumenex",
                    "Cervidil",
                    "Cetirizine",
                    "Cetraxal",
                    "Cetrotide",
                    "Cetuximab",
                    "Chantix",
                    "Chibroxin",
                    "Chlorambucil",
                    "Chloramphenicol Sodium Succinate",
                    "Chloroprocaine",
                    "Chlorpheniramine Maleate",
                    "Chlorpromazine",
                    "Chlorpropamide",
                    "Chlorthalidone",
                    "Cholera Vaccine",
                    "Chorionic Gonadotropin",
                    "Ciclopirox Gel",
                    "Cilostazol",
                    "Cinobac",
                    "Cipro",
                    "Cipro XR",
                    "Cisapride",
                    "Clarinex",
                    "Clarithromycin",
                    "Claritin",
                    "Cleocin",
                    "Cleviprex",
                    "Climara Pro",
                    "Clinoril",
                    "Clobetasol Propionate",
                    "Clocortolone",
                    "Clofarabine",
                    "Clonidine",
                    "Clorazepate Dipotassium",
                    "Clorpres",
                    "Clotrimazole",
                    "Cocaine",
                    "Codeine",
                    "Cognex",
                    "Colazal",
                    "Colchicine",
                    "Colcrys",
                    "Colesevelam Hcl",
                    "Combivir",
                    "Conjugated Estrogens",
                    "Copaxone",
                    "Corgard",
                    "Cosmegen",
                    "Coumadin",
                    "Crolom",
                    "Cromolyn Sodium",
                    "Cubicin",
                    "Curosurf",
                    "Cuvposa",
                    "Cyanocobalamin",
                    "Cyclobenzaprine Hcl",
                    "Cyclophosphamide",
                    "Cyclosporine",
                    "Cylert",
                    "Cymbalta",
                    "Cyproheptadine",
                    "Cystadane",
                    "Cytogam",
                    "Cytomel",
                    "Dacarbazine",
                    "Daraprim",
                    "Darvocet-N",
                    "Darvon Compound",
                    "Dasatinib",
                    "Daunorubicin",
                    "Daypro",
                    "Daypro Alta",
                    "DDAVP Nasal Spray",
                    "Demadex",
                    "Demeclocycline HCl",
                    "Demser",
                    "Depacon",
                    "DepoDur",
                    "Desferal",
                    "Desogen",
                    "Desonate",
                    "DesOwen",
                    "Detrol",
                    "Detrol LA",
                    "Dexlansoprazole",
                    "Dexmethylphenidate Hydrochloride",
                    "Dexrazoxane",
                    "Diamox Sequels",
                    "Dicyclomine",
                    "Didanosine",
                    "Diethylpropion",
                    "Differin",
                    "Diflucan",
                    "Digoxin Immune Fab",
                    "Diovan HCT",
                    "Diphenhydramine",
                    "Diphtheria-Tetanus Vaccine",
                    "Diprolene AF",
                    "Dipyridamole",
                    "Ditropan",
                    "Dobutamine",
                    "Dofetilide",
                    "Dolophine",
                    "Donepezil Hydrochloride",
                    "Dopamine Hydrochloride",
                    "Dopar",
                    "Dopram",
                    "Doral",
                    "Doryx",
                    "Dorzolamide",
                    "Dovonex",
                    "Doxacurium Chloride",
                    "Doxapram",
                    "Doxazosin Mesylate",
                    "Doxepin",
                    "Doxercalciferol",
                    "Doxil",
                    "Doxycycline",
                    "Doxycycline Hyclate",
                    "Drisdol",
                    "Dronabinol",
                    "Drospirenone and Estradiol",
                    "Duetact",
                    "Duraclon",
                    "Dynacirc",
                    "Dynacirc CR",
                    "Dynapen",
                    "Dyphylline",
                    "Econazole Nitrate",
                    "Edrophonium",
                    "Efavirenz",
                    "Elaprase",
                    "Elavil",
                    "Eletriptan hydrobromide",
                    "Eligard",
                    "Ellence",
                    "Elmiron",
                    "Elspar",
                    "Emadine",
                    "Emcyt",
                    "Emedastine",
                    "Empirin",
                    "Emsam",
                    "Emtricitabine",
                    "Emtriva",
                    "Endocet",
                    "Endometrin",
                    "Enflurane",
                    "Engerix-B",
                    "Entereg",
                    "Eovist",
                    "Epinephrine",
                    "Epipen",
                    "Epirubicin hydrochloride",
                    "Epivir",
                    "Equetro",
                    "Eraxis",
                    "Erbitux",
                    "Ergocalciferol",
                    "Erlotinib",
                    "Erythrocin Stearate",
                    "Esomeprazole Sodium",
                    "Essential Amino Acids",
                    "Estrace",
                    "Estradiol",
                    "Estradiol Acetate",
                    "Estradiol valerate",
                    "Estratest",
                    "Estropipate",
                    "Eszopiclone",
                    "Etanercept",
                    "Ethacrynic Acid",
                    "Ethambutol",
                    "Ethinyl Estradiol",
                    "Ethiodol",
                    "Ethosuximide",
                    "Etidocaine HCl",
                    "Etidronate Disodium",
                    "Etopophos",
                    "Etrafon",
                    "Eulexin",
                    "Evista",
                    "Evoxac",
                    "Exelderm",
                    "Exjade",
                    "Extavia",
                    "Factor IX Complex",
                    "Factrel",
                    "Famciclovir",
                    "Famotidine Injection",
                    "Famvir",
                    "Fansidar",
                    "Febuxostat",
                    "Feridex I.V.",
                    "Fesoterodine Fumarate Extended",
                    "Finacea",
                    "Flector",
                    "Flonase",
                    "Florinef",
                    "Floxuridine",
                    "Fluconazole",
                    "Flucytosine",
                    "Fludara",
                    "Fludarabine Phosphate",
                    "Fludrocortisone",
                    "Flumazenil",
                    "FluMist",
                    "Fluocinolone Acetonide",
                    "Fluoroplex",
                    "Fluorouracil",
                    "Fluoxetine Hydrochloride",
                    "Flurbiprofen",
                    "Fluress",
                    "Fluticasone Propionate",
                    "Fluvirin",
                    "FML",
                    "Folic Acid",
                    "Follitropin Alfa",
                    "Follitropin Beta",
                    "Fomepizole",
                    "Foradil Aerolizer",
                    "Foradil Certihaler",
                    "Forane",
                    "Fosamax Plus D",
                    "Fosamprenavir Calcium",
                    "Foscavir",
                    "Fosphenytoin Sodium",
                    "Fragmin",
                    "Frovatriptan Succinate",
                    "Fulvestrant",
                    "Fungizone",
                    "Furadantin",
                    "Furosemide",
                    "Furoxone",
                    "Fuzeon",
                    "Gabitril",
                    "Gadobenate Dimeglumine",
                    "Gadofosveset Trisodium",
                    "Galsulfase",
                    "Gamunex",
                    "Geocillin",
                    "Geodon",
                    "Gleevec",
                    "Glucophage XR",
                    "Glucovance",
                    "Glyburide",
                    "Glycopyrrolate",
                    "Glynase",
                    "Glyset",
                    "Gold Sodium Thiomalate",
                    "Gonadorelin",
                    "Gonal-F",
                    "Gonal-f RFF",
                    "Grifulvin V",
                    "Griseofulvin",
                    "Guanethidine Monosulfate",
                    "Gynazole",
                    "Haemophilus b Conjugate Vaccine",
                    "Halcinonide",
                    "Haldol",
                    "Halobetasol Propionate",
                    "Haloperidol",
                    "Healon",
                    "HepaGam B",
                    "Heparin Lock Flush",
                    "HepatAmine",
                    "Hepatitis A Vaccine, Inactivated",
                    "Hepatitis B Immune Globulin",
                    "Hepflush-10",
                    "Herceptin",
                    "Hexachlorophene",
                    "HibTITER",
                    "Hivid",
                    "Human Secretin",
                    "Humira",
                    "Humulin N",
                    "Hyalgan",
                    "Hydrocodone Bitartrate and Acetaminophen",
                    "Hydroxyethyl Starch",
                    "Hylenex",
                    "Hyoscyamine",
                    "Hytrin",
                    "Ibuprofen Lysine",
                    "Idamycin",
                    "Idamycin PFS",
                    "Ifosfamide",
                    "Iloperidone",
                    "Imipramine",
                    "Imiquimod",
                    "Imitrex",
                    "Immune Globulin",
                    "Immune Globulin Intravenous",
                    "Implanon",
                    "Inderal LA",
                    "Indigo Carmine",
                    "InnoPran XL",
                    "Insulin",
                    "Insulin Aspart",
                    "Intelence",
                    "Intralipid 20%",
                    "Intuniv",
                    "Invanz",
                    "Invega",
                    "Inversine",
                    "Ionamin",
                    "Irinotecan Hydrochloride",
                    "Isentress",
                    "Ismo",
                    "Isocarboxazid",
                    "Isoptin SR",
                    "Isopto Carpine",
                    "Isopto Hyoscine",
                    "Istalol",
                    "Isuprel",
                    "Ixempra",
                    "Jalyn",
                    "Janumet",
                    "Je-Vax",
                    "K-LOR",
                    "Kaletra",
                    "Kariva",
                    "Kenalog",
                    "Kinlytic",
                    "Klonopin",
                    "Kuvan",
                    "Kytril",
                    "Labetalol",
                    "lacosamide",
                    "Lamisil",
                    "Lamivudine / Zidovudine",
                    "Latanoprost",
                    "Letairis",
                    "Letrozole",
                    "Leuprolide Acetate",
                    "Leustatin",
                    "Levalbuterol",
                    "Levaquin",
                    "Levemir",
                    "Levo-T",
                    "Levocabastine",
                    "Levofloxacin",
                    "Levonorgestrel",
                    "Levonorgestrel and Ethinyl Estradiol",
                    "Levonorgestrel Implants",
                    "Levonorgestrel, Ethinyl Estradiol",
                    "Lexapro",
                    "Lexiscan",
                    "Lexxel",
                    "Librium",
                    "Lidex",
                    "Lidoderm",
                    "Linezolid",
                    "Lipofen",
                    "Liposyn II",
                    "Liraglutide",
                    "Lisinopril and Hydrochlorothiazide",
                    "Locoid",
                    "Lodine",
                    "Loperamide Hcl",
                    "Lopid",
                    "Loprox Gel",
                    "Loracarbef",
                    "Lortab",
                    "Lotemax",
                    "Lotensin",
                    "Lotronex",
                    "Lovenox",
                    "Loxapine",
                    "Loxitane",
                    "Lucentis",
                    "Luvox CR",
                    "Lybrel",
                    "M-M-R",
                    "Malarone",
                    "Malathion",
                    "Mandol",
                    "Mangafodipir",
                    "Maraviroc",
                    "Marinol",
                    "Maxitrol",
                    "Mecasermin",
                    "Meclofenamate",
                    "Mefloquine",
                    "Melphalan",
                    "Menactra",
                    "Menest",
                    "Menotropins",
                    "Mephobarbital",
                    "Mequinol and Tretinoin",
                    "Meropenem",
                    "Merrem I.V.",
                    "Mesalamine",
                    "Mesna",
                    "Mestinon",
                    "Metadate ER",
                    "Metaglip",
                    "Metaproterenol Sulfate",
                    "Metaxalone",
                    "Metformin Hcl",
                    "Methadone Hydrochloride",
                    "Methadose Oral Concentrate",
                    "Methazolamide",
                    "Methenamine Hippurate",
                    "Methergine",
                    "Methohexital Sodium",
                    "Methyclothiazide",
                    "Methyldopa",
                    "Methylene Blue",
                    "Methylergonovine Maleate",
                    "Methylin",
                    "Methyltestosterone",
                    "Metipranolol",
                    "Metoclopramide",
                    "Metoprolol Tartrate",
                    "MetroLotion",
                    "Metyrapone",
                    "Metyrosine",
                    "Miacalcin",
                    "Micro-K",
                    "Micronase",
                    "Micronized Glyburide",
                    "Midazolam",
                    "Midodrine Hydrochloride",
                    "Milrinone",
                    "Minocin",
                    "Minocycline",
                    "Minoxidil",
                    "Miochol-E",
                    "Miostat",
                    "Mitomycin",
                    "Mobic",
                    "Modafinil",
                    "Monistat",
                    "Monistat-Derm",
                    "Morrhuate Sodium",
                    "Motrin",
                    "Moxatag",
                    "Mozobil",
                    "Multaq",
                    "Multi Vitamin",
                    "Multihance",
                    "Mustargen",
                    "Mutamycin",
                    "Myambutol",
                    "Mycamine",
                    "Mycelex",
                    "Mycophenolic Acid",
                    "Myfortic",
                    "Mykrox",
                    "Myobloc",
                    "Myochrysine",
                    "Nafcillin Sodium",
                    "Naftifine Hcl",
                    "Nalmefene Hydrochloride",
                    "Naltrexone",
                    "Naproxen",
                    "Nascobal",
                    "Natazia",
                    "Natrecor",
                    "Navelbine",
                    "Nebcin",
                    "Nebivolol Tablets",
                    "Nedocromil",
                    "Nelarabine",
                    "Nelfinavir Mesylate",
                    "NeoProfen",
                    "Neostigmine",
                    "Nephramine",
                    "Nesacaine",
                    "Neulasta",
                    "Nexavar",
                    "Niaspan",
                    "Nicotrol",
                    "Nicotrol NS",
                    "Nilandron",
                    "Nilotinib Capsules",
                    "Nimbex",
                    "Nimotop",
                    "Nitroglycerin",
                    "NitroMist",
                    "Nizatidine",
                    "Nizoral",
                    "Noctec",
                    "Nor-QD",
                    "Norethindrone and Ethinyl Estradiol",
                    "Noritate",
                    "Nortriptyline Hydrochloride",
                    "Norvasc",
                    "NovoLog Mix 70/30",
                    "Novoseven",
                    "Numorphan",
                    "Nutropin AQ",
                    "Nutropin Depot",
                    "Nydrazid",
                    "Omeprazole",
                    "Omnaris",
                    "Opana",
                    "Opticrom",
                    "OptiMARK",
                    "Optipranolol",
                    "Oracea",
                    "Oraqix",
                    "Orfadin",
                    "Orlaam",
                    "Orlistat",
                    "Orudis",
                    "Ovcon",
                    "Ovide",
                    "Oxandrolone",
                    "Oxaprozin",
                    "Oxistat",
                    "Oxsoralen-Ultra",
                    "Oxycodone HCl",
                    "Oxycodone Hydrochloride",
                    "Oxycontin",
                    "Oxymetholone",
                    "Oxymorphone",
                    "Oxytetracycline",
                    "Paclitaxel",
                    "Palifermin",
                    "Paliperidone",
                    "Palonosetron hydrochloride",
                    "Panhematin",
                    "Pantoprazole",
                    "Parafon Forte",
                    "Parnate",
                    "Paser",
                    "Pataday",
                    "Pazopanib",
                    "Pediapred",
                    "PEG 3350",
                    "Pegfilgrastim",
                    "Pemirolast Potassium",
                    "Penciclovir",
                    "Penicillamine",
                    "Penlac",
                    "Pentetate Zinc Trisodium",
                    "Pentobarbital",
                    "Pentoxifylline",
                    "Perflutren",
                    "Perindopril Erbumine",
                    "Permax",
                    "Persantine",
                    "Pfizerpen",
                    "Phenazopyridine",
                    "Phenelzine",
                    "Phenobarbital",
                    "Phenoxybenzamine",
                    "Phenylephrine HCl",
                    "Phenylephrine Hydrochloride",
                    "Phenytoin",
                    "Phosphate",
                    "Photofrin",
                    "Pilocarpine Hydrochloride",
                    "Pilopine HS",
                    "Pindolol",
                    "Pipracil",
                    "Piroxicam",
                    "Plaquenil",
                    "PlasmaLyte A",
                    "Plavix",
                    "Plenaxis",
                    "Pletal",
                    "Pneumovax",
                    "Podophyllin",
                    "Polidocanol",
                    "Polyethylene Glycol 3350",
                    "Polythiazide",
                    "Pramipexole",
                    "Pred-G",
                    "Prednicarbate",
                    "Prednisolone Acetate",
                    "Prednisone",
                    "Prefest",
                    "Pregnyl",
                    "Premarin",
                    "Prepidil",
                    "Prevpac",
                    "Priftin",
                    "Primacor",
                    "Primaquine",
                    "Primidone",
                    "Prinivil",
                    "Prinzide",
                    "Pristiq",
                    "Procainamide",
                    "Procalamine",
                    "Prochlorperazine Maleate",
                    "ProHance",
                    "Proleukin",
                    "Prolixin",
                    "Promethazine HCl",
                    "Promethazine Hydrochloride",
                    "Prometrium",
                    "Propecia",
                    "Proquin XR",
                    "Prostin VR Pediatric",
                    "Protein C Concentrate",
                    "Protopic",
                    "Protriptyline Hydrochloride",
                    "Proventil HFA",
                    "Provisc",
                    "Provocholine",
                    "Pulmicort Flexhaler",
                    "Pylera",
                    "Pyrazinamide",
                    "Pyridium",
                    "Pyridostigmine",
                    "Qualaquin",
                    "Quazepam",
                    "Quinidine Sulfate",
                    "Quixin",
                    "Rabies Vaccine",
                    "Raltegravir",
                    "Ranexa",
                    "Ranitidine Hcl",
                    "Rapamune",
                    "Rasagiline",
                    "Raxar",
                    "Rebetol",
                    "Remicade",
                    "Remifentanil",
                    "Renese",
                    "ReoPro",
                    "Rescriptor",
                    "Rescula",
                    "Revatio",
                    "Revex",
                    "Revia",
                    "Reyataz",
                    "Rezulin",
                    "Rhinocort Aqua",
                    "Rhogam Ultra-Filtered Plus",
                    "RiaSTAP",
                    "Rifamate",
                    "Riomet",
                    "Risperidone",
                    "Ritalin",
                    "Rituximab",
                    "Rivastigmine Tartrate",
                    "Robinul",
                    "Rosiglitazone Maleate",
                    "Rotarix",
                    "RotaTeq",
                    "Roxicet",
                    "Roxicodone",
                    "Ryzolt",
                    "Sabril",
                    "Sacrosidase",
                    "Samsca",
                    "Sanctura",
                    "Santyl",
                    "Saphris",
                    "Scopolamine",
                    "Seasonale",
                    "Selegiline Hydrochloride",
                    "Selsun",
                    "Septra",
                    "Serax",
                    "Sertraline Hcl",
                    "Serzone",
                    "Sevoflurane",
                    "Sibutramine Hydrochloride Monohydrate",
                    "Silenor",
                    "Simponi",
                    "Sirolimus",
                    "Sitagliptin Metformin HCL",
                    "Slow-K",
                    "Sodium Bicarbonate",
                    "Sodium ferric gluconate",
                    "Sodium Iodide I 131",
                    "Sodium Polystyrene Sulfonate",
                    "Sodium Sulfacetamide",
                    "Soma Compound",
                    "Somatrem",
                    "Somatropin",
                    "Sonata",
                    "Soriatane",
                    "Sotradecol",
                    "Spiriva",
                    "Sporanox",
                    "Sprix",
                    "Sprycel",
                    "Stalevo",
                    "Starlix",
                    "Stavudine",
                    "Streptokinase",
                    "Strontium-89",
                    "Suboxone",
                    "Succimer",
                    "Succinylcholine Chloride",
                    "Sucralfate",
                    "Sulfamylon",
                    "Sunitinib Malate",
                    "Sutent",
                    "Synthroid",
                    "Synvisc",
                    "Syprine",
                    "Tacrolimus",
                    "Talacen",
                    "Talwin Nx",
                    "Tamiflu",
                    "Tamoxifen Citrate",
                    "Tapazole",
                    "Targretin",
                    "Tasmar",
                    "Tegretol",
                    "Tekturna HCT",
                    "Telavancin",
                    "Telbivudine",
                    "Telmisartan",
                    "Temovate Scalp",
                    "Temozolomide",
                    "Temsirolimus",
                    "Teniposide",
                    "Terazol 3, Terazol 7",
                    "Tessalon",
                    "Testolactone",
                    "Testred",
                    "Teveten HCT",
                    "Theracys",
                    "Thiabendazole",
                    "Thiethylperazine",
                    "Thiopental Sodium",
                    "Thioridazine",
                    "Thiothixene Hcl",
                    "Thrombin",
                    "Thyrolar",
                    "Thyrotropin Alfa",
                    "Tiazac",
                    "Ticarcillin",
                    "Tinzaparin",
                    "Tirosint",
                    "Tizanidine",
                    "Tobrex",
                    "Tofranil-PM",
                    "Tolazamide",
                    "Tolmetin Sodium",
                    "Tonocard",
                    "Topicort",
                    "Topiramate",
                    "Topotecan Hydrochloride",
                    "Toradol",
                    "Torsemide",
                    "Toviaz",
                    "Tramadol Hcl",
                    "Tranxene",
                    "Trastuzumab",
                    "Trasylol",
                    "Tretinoin",
                    "Trexall",
                    "Tri-Sprintec",
                    "Triamcinolone Acetonide",
                    "Triazolam",
                    "Tribenzor",
                    "Trientine",
                    "Trihexyphenidyl",
                    "Trilipix",
                    "Trilisate",
                    "Trimethadione",
                    "Trimethoprim",
                    "Trimethoprim and Sulfamethoxazole",
                    "Trimetrexate Glucuronate",
                    "Trizivir",
                    "Trovafloxacin",
                    "Trovan",
                    "Trusopt",
                    "Trypan Blue",
                    "Tussionex",
                    "Tysabri",
                    "Tyvaso",
                    "Uloric",
                    "Ultiva",
                    "Ultram",
                    "Ultrase",
                    "Ultravate",
                    "Unasyn",
                    "Urex",
                    "Ursodiol",
                    "Vagistat-1",
                    "Valacyclovir Hydrochloride",
                    "Valganciclovir Hcl",
                    "Valium",
                    "Valproic Acid",
                    "Valsartan and Hydrochlorothiazide",
                    "Vancomycin Hydrochloride",
                    "Vaprisol",
                    "Vasocidin",
                    "Vasotec",
                    "Vasovist",
                    "Vectibix",
                    "Vectical",
                    "Velosulin",
                    "Veltin",
                    "Venlafaxine Hydrochloride",
                    "Veramyst",
                    "Vermox",
                    "Vesanoid",
                    "VESIcare",
                    "Vibramycin",
                    "Vicodin",
                    "Vicodin HP",
                    "Vicoprofen",
                    "Victoza",
                    "Vimovo",
                    "Vimpat",
                    "Vinblastine Sulfate",
                    "Viokase",
                    "Vioxx",
                    "Viread",
                    "VisionBlue",
                    "Vistide",
                    "Vitamin K1",
                    "Vivactil",
                    "Vivelle-Dot",
                    "Vusion",
                    "Vytorin",
                    "Winstrol",
                    "Xigris",
                    "Xolair",
                    "Yellow Fever Vaccine",
                    "Zaditor",
                    "Zalcitabine",
                    "Zanosar",
                    "Zelnorm",
                    "Zemaira",
                    "Zemplar",
                    "Zestoretic",
                    "Zestril",
                    "Ziconotide",
                    "Zingo",
                    "Zmax",
                    "Zocor",
                    "Zolinza",
                    "Zolmitriptan",
                    "Zonalon",
                    "Zoster Vaccine Live",
                    "Zosyn",
                    "Zyclara",
                    "Zyflo",
                    "Zylet",
                    "Zyloprim",
                    "Zymaxid"
            )
            val list = java.util.ArrayList<String>()
            for (i in med.indices) {
                list.add(med[i])
            }

            val adapter1 = ArrayAdapter(
                    this, R.layout.single_layout_medicine, list)
            mDialogView.medicine_name.setAdapter(adapter1)
            mDialogView.medicine_name.setThreshold(1)
            mDialogView.yes.setOnClickListener {


                val name = mDialogView.medicine_name.text.toString()
                val quantity = mDialogView.quantity.text.toString()
                val morning = mDialogView.morning.text.toString()
                val afternoon = mDialogView.afternoon.text.toString()
                val evening = mDialogView.evening.text.toString()
                val night = mDialogView.night.text.toString()
                if (!name.isEmpty() && !quantity.isEmpty() && !morning.isEmpty() && !afternoon.isEmpty() && !evening.isEmpty() && !night.isEmpty()) {
                    users.add(Medicine(name, morning, afternoon, evening, night, quantity))
                    mAlertDialog.dismiss()
                }else{
                    Toast.makeText(applicationContext,"Fill all Details.",Toast.LENGTH_SHORT).show()
                }

            }
            mDialogView.no.setOnClickListener {
                mAlertDialog.dismiss()
            }
        }

        val adapter = MedicineAdapter(users)
        recyclerView.adapter = adapter
        val submit = findViewById(R.id.add_prescription_approve) as FloatingActionButton
        val postListener = object : ValueEventListener {
            override fun onDataChange(dataSnapshot: DataSnapshot) {


                var name = dataSnapshot.child("name").value!!.toString()
                var email = dataSnapshot.child("email_id").value!!.toString()

                submit.setOnClickListener {

                        if (!edit_text_details.text.toString().isEmpty() && !users.isEmpty()) {

                            val sdf = SimpleDateFormat("dd/MMM/yyyy hh:mm:ss")
                            val calendar = Calendar.getInstance()
                            val currentDate = sdf.format(calendar.getTime())
                            var hashMap: HashMap<String, String> = HashMap<String, String>()
                            hashMap.put("user_id", userObject.User_Id)
                            hashMap.put("key", key)
                            hashMap.put("name", userObject.Name)
                            hashMap.put("city", userObject.City)
                            hashMap.put("state", userObject.State)
                            hashMap.put("gender", userObject.Gender)
                            hashMap.put("country", userObject.Country)
                            hashMap.put("age", userObject.Age)
                            hashMap.put("timestamp", currentDate)
                            hashMap.put("profile_image", userObject.Profile_Image)
                            hashMap.put("email", userObject.Email)
                            hashMap.put("details", edit_text_details.text.toString())

                            mPatientDatabase.child(key).setValue(hashMap).addOnCompleteListener { task ->
                                if (task.isSuccessful) {

                                    var hashMap1: HashMap<String, ArrayList<Medicine>> = HashMap<String, ArrayList<Medicine>>()
                                    hashMap1.put("medicine", users)
                                    mPatientDatabase.child(key).updateChildren(hashMap1 as Map<String, Any>?).addOnCompleteListener { task1 ->
                                        if (task1.isSuccessful) {
                                            val user = PrescriptionObjects(key, mCurrentUserId.toString(), name, currentDate, email,
                                                    users, edit_text_details.text.toString(),
                                                    dataSnapshot.child("profile_image").value!!.toString())
                                            val serializeString = Gson().toJson(user)
                                            val encryptedString = EncryptionHelper.getInstance().encryptionString(serializeString).encryptMsg()
                                            setImageBitmap(encryptedString)
                                        }
                                    }


                                }
                            }
                        } else {
                            Toast.makeText(applicationContext, "Complete all Details or Add Prescriptions", Toast.LENGTH_SHORT).show()
                        }


                }

            }

            override fun onCancelled(databaseError: DatabaseError) {

            }
        }
        mUserDatabase.addValueEventListener(postListener)


    }

    private fun setImageBitmap(encryptedString: String?) {
        val bitmap = QRCodeHelper.newInstance(this).setContent(encryptedString).setErrorCorrectionLevel(ErrorCorrectionLevel.Q).setMargin(2).qrcOde
        val mDialogView = LayoutInflater.from(this).inflate(R.layout.activity_qrcode, null)
        val mBuilder = AlertDialog.Builder(this)
                .setView(mDialogView)
                .setTitle("Your QR Code")
        val  mAlertDialog = mBuilder.show()
        mAlertDialog.qrcode.setImageBitmap(bitmap)
    }


}
